include:
   - infra.yaml
services:
  web:
    build: .
    ports:
      - "5050:5050"
    develop:
      watch: # Modo Watch
        - action: sync
          path: .
          target: /app # AQUI SYNC!!